FROM node:22-alpine AS builder

WORKDIR /app

COPY my-app/package*.json ./

RUN npm install

COPY my-app/ .

RUN npm run build

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
